version: "3.7"

services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
    volumes:
      - ./:/app